
services:
  postgres:
    image: postgres:10
    restart: always
    network_mode: "host"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_DB: "demodb"
    #   POSTGRES_USER: "demouser"
    #   POSTGRES_PASSWORD: "DemoPa$$"
    ports:
      - "5432:5432"

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile.spring-boot-app
    network_mode: "host"
    depends_on:
      - postgres
      - node-app
    # environment:
    #   # Override datasource URL to point to the postgres container
    #   SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/demodb"
    #   SPRING_DATASOURCE_PASSWORD: "DemoPa$$"
    #   # Override node-app URL to use the container name (instead of localhost)
    #   APP_NODE_URL: "http://host.docker.internal:8081/"
    ports:
      - "8080:8080"
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node-app
    network_mode: "host"
    ports:
      - "8081:8081"

volumes:
  pgdata:
